/**
 * upload.js — Admin Upload & Form Logic
 * ──────────────────────────────────────
 * Dynamic form: one row per reading (date + track + time + temp).
 * Rows are generated by OCR or added manually with the "+ Add Row" button.
 * Each row has its own track selector — matches actual NATRAX sheet format.
 */

const Upload = (() => {

  // Internal state: array of row objects currently in the form
  let _rows = [];

  // ── Initialise listeners ──────────────────────────────

  function initListeners() {
    const dropZone  = document.getElementById("dropZone");
    const fileInput = document.getElementById("fileInput");
    const selectBtn = document.getElementById("selectFileBtn");
    const clearBtn  = document.getElementById("clearFormBtn");
    const saveBtn   = document.getElementById("saveBtn");
    const addRowBtn = document.getElementById("addRowBtn");

    selectBtn?.addEventListener("click", () => fileInput?.click());

    fileInput?.addEventListener("change", e => {
      const file = e.target.files?.[0];
      if (file) OCR.processImage(file);
    });

    dropZone?.addEventListener("dragover", e => {
      e.preventDefault();
      dropZone.classList.add("dragover");
    });
    dropZone?.addEventListener("dragleave", () => dropZone.classList.remove("dragover"));
    dropZone?.addEventListener("drop", e => {
      e.preventDefault();
      dropZone.classList.remove("dragover");
      const file = e.dataTransfer?.files?.[0];
      if (file && file.type.startsWith("image/")) {
        OCR.processImage(file);
      } else {
        App.showToast("Please drop an image file");
      }
    });
    dropZone?.addEventListener("keydown", e => {
      if (e.key === "Enter" || e.key === " ") fileInput?.click();
    });

    clearBtn?.addEventListener("click", clearForm);
    saveBtn?.addEventListener("click", handleSave);
    addRowBtn?.addEventListener("click", () => addBlankRow());
  }

  // ── Row rendering ─────────────────────────────────────

  /**
   * Render rows from OCR or manual addition into the dynamic table.
   * Called by OCR.populateForm() after extraction.
   * @param {Array} rows - [{date, track, time, temp}]
   */
  function renderRows(rows) {
    _rows = rows.map((r, i) => ({ ...r, id: i }));
    rebuildTable();
  }

  /**
   * Add one blank row to the form (for manual entry).
   */
  function addBlankRow() {
    const id = _rows.length;
    // Inherit date from last row if available
    const lastDate = _rows.length > 0 ? _rows[_rows.length - 1].date : "";
    _rows.push({ id, date: lastDate, track: "", time: "", temp: "" });
    rebuildTable();
    // Focus the track select of the new row
    setTimeout(() => {
      const selects = document.querySelectorAll(".row-track");
      selects[selects.length - 1]?.focus();
    }, 50);
  }

  /**
   * Rebuild the entire readings table from _rows state.
   * Each row: [Date] [Track] [Time] [Temp °C] [Delete]
   */
  function rebuildTable() {
    const container = document.getElementById("dynamicRowsContainer");
    if (!container) return;

    if (_rows.length === 0) {
      container.innerHTML = `<div class="no-rows-hint">No readings yet — upload an image or click "+ Add Row"</div>`;
      return;
    }

    container.innerHTML = `
      <div class="dyn-table-header">
        <span>Date</span>
        <span>Track</span>
        <span>Time</span>
        <span>Temp °C</span>
        <span></span>
      </div>
      ${_rows.map(r => `
        <div class="dyn-row" data-id="${r.id}">
          <input type="date"   class="form-input row-date"  value="${r.date  || ""}" data-field="date"  />
          <select              class="form-input row-track"                           data-field="track">
            <option value=""   ${!r.track         ? "selected":""}>—</option>
            <option value="T3" ${r.track === "T3"  ? "selected":""}>T3</option>
            <option value="T13"${r.track === "T13" ? "selected":""}>T13</option>
          </select>
          <input type="time"   class="form-input row-time"  value="${r.time  || ""}" data-field="time"  />
          <input type="number" class="form-input row-temp"  value="${r.temp  || ""}" data-field="temp"
                 step="0.1" min="0" max="120" placeholder="°C" />
          <button class="delete-row-btn" data-id="${r.id}" title="Remove row" aria-label="Remove row">✕</button>
        </div>
      `).join("")}
    `;

    // Live-sync inputs back to _rows state
    container.querySelectorAll(".dyn-row").forEach(rowEl => {
      const id = parseInt(rowEl.dataset.id);
      rowEl.querySelectorAll("[data-field]").forEach(input => {
        input.addEventListener("change", e => {
          const row = _rows.find(r => r.id === id);
          if (row) row[e.target.dataset.field] = e.target.value;
        });
      });
    });

    // Delete row buttons
    container.querySelectorAll(".delete-row-btn").forEach(btn => {
      btn.addEventListener("click", () => {
        const id = parseInt(btn.dataset.id);
        _rows = _rows.filter(r => r.id !== id);
        rebuildTable();
      });
    });
  }

  // ── Form clear ────────────────────────────────────────

  function clearForm() {
    _rows = [];
    rebuildTable();
    document.getElementById("ocrStatus")?.classList.add("hidden");
    document.getElementById("previewWrap")?.classList.add("hidden");
    document.getElementById("saveStatus")?.classList.add("hidden");
    const label = document.getElementById("weatherFetchLabel");
    if (label) label.textContent = "Weather data will be fetched automatically on save";
  }

  // ── Read rows from DOM (latest values) ───────────────

  function readFormRows() {
    // Sync latest DOM values into _rows before reading
    const container = document.getElementById("dynamicRowsContainer");
    container?.querySelectorAll(".dyn-row").forEach(rowEl => {
      const id  = parseInt(rowEl.dataset.id);
      const row = _rows.find(r => r.id === id);
      if (!row) return;
      row.date  = rowEl.querySelector(".row-date")?.value  || "";
      row.track = rowEl.querySelector(".row-track")?.value || "";
      row.time  = rowEl.querySelector(".row-time")?.value  || "";
      row.temp  = rowEl.querySelector(".row-temp")?.value  || "";
    });

    const valid = _rows.filter(r => r.date && r.track && r.time && r.temp !== "");
    const invalid = _rows.length - valid.length;

    if (valid.length === 0) {
      App.showToast("No complete rows to save — each row needs date, track, time and temp");
      return null;
    }
    if (invalid > 0) {
      App.showToast(`${invalid} incomplete row(s) will be skipped`);
    }
    return valid;
  }

  // ── Save handler ──────────────────────────────────────

  async function handleSave() {
    const saveBtn      = document.getElementById("saveBtn");
    const statusEl     = document.getElementById("saveStatus");
    const weatherLabel = document.getElementById("weatherFetchLabel");

    const validRows = readFormRows();
    if (!validRows) return;

    saveBtn.disabled = true;
    statusEl.className = "save-status";
    statusEl.classList.remove("hidden");
    statusEl.textContent = `Fetching weather for ${validRows.length} reading(s)…`;
    if (weatherLabel) weatherLabel.textContent = "Fetching weather data…";

    try {
      const enrichedRows = await Promise.all(validRows.map(async row => {
        let weather = { ambientTemp: null, humidity: null, windSpeed: null };
        try {
          weather = await API.fetchWeatherForDateTime(row.date, row.time);
        } catch (e) {
          console.warn("[NATRAX] Weather fetch failed for:", row, e);
        }
        return {
          date:        row.date,
          time:        row.time,
          track:       row.track,
          surfaceTemp: parseFloat(row.temp),
          ambientTemp: weather.ambientTemp,
          windSpeed:   weather.windSpeed,
          humidity:    weather.humidity,
          source:      "OCR+Manual",
        };
      }));

      if (weatherLabel) weatherLabel.textContent = "Weather fetched ✓";
      statusEl.textContent = "Saving to Google Sheet…";

      const token  = Auth.getToken();
      const result = await API.saveRows(enrichedRows, token);

      statusEl.className = "save-status success";
      statusEl.textContent = `✓ Saved ${result.saved} record(s). Skipped ${result.skipped} duplicate(s).`;
      App.showToast(`Saved ${result.saved} record(s) successfully`);

      await App.loadData();
      clearForm();

    } catch (err) {
      statusEl.className = "save-status error";
      statusEl.textContent = `Error: ${err.message}`;
      App.showToast("Save failed — see form for details");
      console.error("[NATRAX Upload] Save error:", err);
    } finally {
      saveBtn.disabled = false;
    }
  }

  return { initListeners, clearForm, renderRows };
})();
